{% set version = "3.2" %}
{% set sha256 = "e0ddadebb396906a3e3e4cac2f697c8d6ab92dffa5d365a5bc23c7d41d30ef62" %}

package:
  name: gperf
  version: {{ version }}

source:
  url: http://ftp.gnu.org/pub/gnu/gperf/gperf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - sed  # [osx]

test:
  commands:
    - gperf --help
    - gperf --version

about:
  home: https://www.gnu.org/software/gperf/
  dev_url: http://savannah.gnu.org/projects/gperf/
  doc_url: https://www.gnu.org/software/gperf/manual/gperf.html
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: GNU gperf is a perfect hash function generator.

extra:
  recipe-maintainers:
    - mbargull
    - tfors
