{% set version = "3.3" %}
{% set sha256 = "fd87e0aba7e43ae054837afd6cd4db03a3f2693deb3619085e6ed9d8d9604ad8" %}

package:
  name: gperf
  version: "{{ version }}"

source:
  url: http://ftp.gnu.org/pub/gnu/gperf/gperf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2

requirements:
  build:
    - gnuconfig  # [unix or win_arm64]
    - {{ compiler('c') }}          # [unix or win_arm64]
    - {{ compiler('cxx') }}        # [unix or win_arm64]
    - {{ stdlib('c') }}            # [unix or win_arm64]
    - {{ compiler('m2w64_c') }}    # [win and not win_arm64]
    - {{ compiler('m2w64_cxx') }}  # [win and not win_arm64]
    - {{ stdlib('m2w64_c') }}      # [win and not win_arm64]
    - make  # [not win_arm64]
    - autotools_clang_conda  # [win_arm64]
    - m2-base  # [win and not win_arm64]
    - m2-bash  # [win and not win_arm64]
    - m2-sed   # [win and not win_arm64]
    - sed      # [osx]

test:
  requires:
    - {{ compiler('c') }}  # [win_arm64]
    - {{ stdlib('c') }}  # [win_arm64]
  files:
    - keywords.gperf  # [win_arm64]
    - check_lookup.c  # [win_arm64]
  commands:
    - gperf --help         # [unix]
    - gperf --version      # [unix]
    - gperf.exe --help     # [win]
    - gperf.exe --version  # [win]

about:
  home: https://www.gnu.org/software/gperf/
  dev_url: http://savannah.gnu.org/projects/gperf/
  doc_url: https://www.gnu.org/software/gperf/manual/gperf.html
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: GNU gperf is a perfect hash function generator.

extra:
  recipe-maintainers:
    - mbargull
    - tfors
    - isuruf
    - luhenry
